Future branch first
MDnull98/GETmerger pull request #4
Opened 2019-03-28 14:19 UTC by MDnull98

2019-03-28 14:34 UTC, horbel requested changes

2019-03-28 14:34 UTC, horbel commented on GETmerger/GETmerger.Core/QueryRepositories/BaseQueryRepository.cs
> +        protected SqlConnection getConnection()
С большой буквы название метода

2019-03-28 14:34 UTC, horbel commented on GETmerger/GETmerger.DAL.Contracts/QueryRepositories/IDBQueryRepository.cs
> +
Пустая строка

2019-03-28 14:48 UTC, ShakunVasiliy commented on GETmerger/GETmarger.Core.Contracts/Class1.cs
> +    public class Class1
Нужно удалить этот класс

2019-03-28 14:59 UTC, ShakunVasiliy commented on GETmerger/GETmerger.BLL.Contracts/Models/Output/DatabasesOutputModels.cs
> +        public IEnumerable<string> Names { get; set; }
Тебе на UI нужно будет список баз данных.
Также ты должен на UI знать об названии и ид базы.

2019-03-28 15:22 UTC, horbel commented
Done

2019-03-28 15:25 UTC, horbel approved these changes

2019-03-28 15:25 UTC, merged

2019-03-29 06:57 UTC, ShakunVasiliy commented on GETmerger/GETmerger.DAL.Contracts/EF/MergerContext.cs
> +        public DbSet<BaseName> Bases { get; set; }
Подумай: нужен ли тебе этот dbset.

2019-03-29 06:58 UTC, ShakunVasiliy commented on GETmerger/GETmerger.DAL.Contracts/EF/MergerContext.cs
> +        public DbSet<TableName> Tables { get; set; }
Тоже что и для свойства Bases.

2019-03-29 07:00 UTC, ShakunVasiliy commented on GETmerger/GETmerger.DAL.Contracts/Interfaces/IBaseRepository.cs
> +    public interface IBaseRepository:IRepository<BaseName>
Подумай: действительно ли тебе нужен этот repository-ий.

2019-03-29 07:01 UTC, ShakunVasiliy commented on GETmerger/GETmerger.DAL.Contracts/Interfaces/ITableRepository.cs
> +    public interface ITableRepository:IRepository<TableName>
тоже самое что и для IBaseRepository (dal.contracts.interfaces)

2019-03-29 07:05 UTC, ShakunVasiliy commented on GETmerger/GETmerger.DAL.Contracts/Models/BaseName.cs
> +    public class BaseName
Название класса выбрано неудачно. Подумай, какое имя будет точнее отражать суть этого объекта.

2019-03-29 07:07 UTC, ShakunVasiliy commented on GETmerger/GETmerger.DAL.Contracts/Models/TableName.cs
> +    public class TableName
Здесь тоже название выбрано неудачно. Нужен ли тебе этот объект?

2019-03-29 07:10 UTC, ShakunVasiliy commented on GETmerger/GETmerger.DAL/Repositories/BaseRepository.cs
> +        public List<BaseName> GetAll()
Не думаю, что базовый класс должен знать о какой-то конкретной модели.

2019-03-29 07:11 UTC, ShakunVasiliy commented on GETmerger/GETmerger.DAL/Repositories/BaseRepository.cs
> +        public void Create(BaseName item)
Аналогично (Не думаю, что базовый класс должен знать о какой-то конкретной модели).

2019-03-29 07:11 UTC, ShakunVasiliy commented on GETmerger/GETmerger.DAL/Repositories/BaseRepository.cs
> +        public BaseName Get(int? id)
Аналогично (Не думаю, что базовый класс должен знать о какой-то конкретной модели).

2019-03-29 07:11 UTC, ShakunVasiliy commented on GETmerger/GETmerger.DAL/Repositories/BaseRepository.cs
> +        public void Update(BaseName item)
Аналогично (Не думаю, что базовый класс должен знать о какой-то конкретной модели).

2019-03-29 07:15 UTC, ShakunVasiliy commented on GETmerger/GETmerger.DAL/Repositories/BaseRepository.cs
> +    public class BaseRepository : IBaseRepository
Название не совсем удачно выбрано, т.к. на первый взгляд принимаешь этот класс как базовый для всех остальных repository-ев. (просто Base в названиях  класса лучше не использовать, если класс не предназначен для последующего наследования его в логической группе классов).